on: 
    pull_request: 
        branches: dev
    
jobs:
    check_pr_size:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - id: get_total_lines_changed
              run: |
                size=$(git diff --stat origin/dev \
                | grep -v .lock \
                | grep -v Bin \
                | awk -F"|" '{ print $2 }' \
                | awk '{ print $1 }' \
                | sed '/^$/d' \
                | paste -sd+ - \
                | bc)
    
                echo "size=${size}" >> $GITHUB_ENV
                echo ""
                echo "Total lines changed (note: *.lock files are excluded from this count): "
                echo $size

            - name: Add comment to PR
              env:
                  URL: ${{ github.event.pull_request.comments_url }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  curl \
                    -X POST \
                    $URL \
                    -H "Content-Type: application/json" \
                    -H "Authorization: token $GITHUB_TOKEN" \
                    --data '{ "body": "blah blah" }'
   
            - run: |
                if [[ $size -gt 600 ]]
                then
                    echo "Warning - total lines changed is greater than" 600.
                    echo "Please consider breaking this PR down."
                    exit 1
                fi
