on: 
    pull_request: 
        branches: dev

permissions: write-all

jobs:
    check_pr_size:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - id: get_total_lines_changed
              run: |
                size=$(git diff --stat origin/dev \
                | grep -v .lock \
                | grep -v Bin \
                | awk -F"|" '{ print $2 }' \
                | awk '{ print $1 }' \
                | sed '/^$/d' \
                | paste -sd+ - \
                | bc)
    
                echo "size=${size}" >> $GITHUB_ENV
                echo ""
                echo "Total lines changed (note: *.lock files are excluded from this count): "
                echo $size

            - name: send message to pr
              env: 
                URL : ${{ github.event.pull_request.comments_url }}
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                body: "# Pull Request de $size Líneas de Código \n ¡Hola compañeros de equipo! He creado un Pull Request que contiene un total de $size líneas de código, ¡y estoy emocionado de compartirlo con ustedes!"
              run: |
                curl \
                -X POST \
                $URL \
                -H "Content-Type: application/json" \
                -H "Authorization: token $GITHUB_TOKEN" \
                --data '{"body": $body }'  

            - run: |
                if [[ $size -gt 600 ]]
                then
                    echo "Warning - total lines changed is greater than" 600.
                    echo "Please consider breaking this PR down."
                    exit 1
                fi
            